# collision_boxes:                     # todo: add other primitives.
# - id:               ceiling
#   pose:
#     position:
#       x:            0.0
#       y:            0.0
#       z:            0.75
#     orientation:
#       x:            0.0
#       y:            0.0
#       z:            0.0
#       w:            1.0
#   dimension:
#     x:              1.2
#     y:              0.8
#     z:              0.01
#
# - id:               right_wall
#   pose:
#     position:
#       x:            0.0
#       y:            0.42
#       z:            0.0
#     orientation:
#       x:            0.0
#       y:            0.0
#       z:            0.0
#       w:            1.0
#   dimension:
#     x:              1.2
#     y:              0.01
#     z:              1.6
#
# - id:               left_wall
#   pose:
#     position:
#       x:            0.0
#       y:            -0.42
#       z:            0.0
#     orientation:
#       x:            0.0
#       y:            0.0
#       z:            0.0
#       w:            1.0
#   dimension:
#     x:              1.2
#     y:              0.01
#     z:              1.6
#
# - id:               back_wall
#   pose:
#     position:
#       x:            -0.34
#       y:            0.0
#       z:            0.0
#     orientation:
#       x:            0.0
#       y:            0.0
#       z:            0.0
#       w:            1.0
#   dimension:
#     x:              0.01
#     y:              0.8
#     z:              1.6
