limit_joint_4:                         true
camera_frame:                          sr300_depth_optical_frame
velocity_scaling:                      0.1
do_rotation:                           false

grasp_object:
  current_threshold:                    70

place_object:
  force_threshold:                     3
  incremental_movement_timeout:        30
  incremental_movement_distance:       -0.05
  approaching_distance:                0.1
  approaching_distance_release:        0.1
