configuration:
#- id:  stone_9
#  pose:
#   position:
#      x:            0.112199
#      y:            0.304122
#      z:            0.0412905
#   orientation:
#      x:            0.861328
#      y:            -0.507737
#      z:            -0.017783
#      w:            0.000771582
#- id:  stone_4
#  pose:
#   position:
#      x:            0.112495
#      y:            0.308632
#      z:            0.0795505
#   orientation:
#      x:            0.01093
#      y:            0.995573
#      z:            -0.0753466
#      w:            -0.0551238
#- id:  stone_8
#  pose:
#   position:
#      x:            0.0944704
#      y:            0.311537
#      z:            0.111134
#   orientation:
#      x:            0.784619
#      y:            -0.600999
#      z:            -0.102457
#      w:            0.112591
#- id:  stone_2
#  pose:
#   position:
#      x:            0.106717
#      y:            0.300409
#      z:            0.147952
#   orientation:
#      x:            0.0652062
#      y:            0.0589839
#      z:            0.765061
#      w:            0.637927
#- id:  stone_7
#  pose:
#   position:
#      x:            0.0945719
#      y:            0.313136
#      z:            0.17757
#   orientation:
#      x:            0.925058
#      y:            0.102049
#      z:            0.357109
#      w:            0.0795394
#


##################
- id:  stone_9
  pose:
   position:
      x:            0.127687
      y:            0.287259
      z:            0.0398587
   orientation:
      x:            0.882078
      y:            -0.471071
      z:            -0.00223404
      w:            -0.00495314
- id:  stone_4
  pose:
   position:
      x:            0.122926
      y:            0.291406
      z:            0.0791263
   orientation:
      x:            0.118552
      y:            0.988246
      z:            -0.0753927
      w:            -0.0602643
- id:  stone_7
  pose:
   position:
      x:            0.11293
      y:            0.29311
      z:            0.118754
   orientation:
      x:            0.964093
      y:            0.124202
      z:            0.222018
      w:            0.0761982

#
#- id:  stone_8
#  pose:
#   position:
#      x:            0.103616
#      y:            0.298162
#      z:            0.0764959
#   orientation:
#      x:            0.698622
#      y:            -0.681523
#      z:            -0.131534
#      w:            0.173646
#- id:  stone_7
#  pose:
#   position:
#      x:            0.103169
#      y:            0.282676
#      z:            0.125696
#   orientation:
#      x:            0.707064
#      y:            0.692254
#      z:            -0.0149057
#      w:            -0.143608




#- id:  stone_2
#  pose:
#   position:
#      x:            0.123094
#      y:            0.288016
#      z:            0.115907
#   orientation:
#      x:            -0.257682
#      y:            0.050255
#      z:            -0.670334
#      w:            0.694065



##################
#- id:  stone_8
#  pose:
#   position:
#      x:            0.112
#      y:            0.30396
#      z:            0.0159508
#   orientation:
#      x:            0.83073
#      y:            -0.524234
#      z:            -0.099748
#      w:            0.15848
#
#- id:  stone_2
#  pose:
#   position:
#      x:            0.123864
#      y:            0.287597
#      z:            0.0553135
#   orientation:
#      x:            0.0336321
#      y:            0.0448361
#      z:            0.814251
#      w:            0.577801
#
#- id:  stone_7
#  pose:
#   position:
#      x:            0.112688
#      y:            0.289031
#      z:            0.085472
#   orientation:
#      x:            0.76671
#      y:            0.624368
#      z:            0.14793
#      w:            0.0208837

##########################
#
#- id:  stone_5
#  pose:
#   position:
#      x:            0.118095
#      y:            0.32251
#      z:            0.031214
#   orientation:
#      x:            -0.483672
#      y:            -0.417076
#      z:            -0.38912
#      w:            0.663848
#
#- id:  stone_8
#  pose:
#   position:
#      x:            0.12477
#      y:            0.334049
#      z:            0.0702053
#   orientation:
#      x:            -0.575399
#      y:            0.792689
#      z:            0.162498
#      w:            -0.118973
